name: E SPORT
title: E SPORT 1
description: The best source for E-Sports news.
url: "https://kinanmjeed88.github.io"
baseurl: "/E-SPORT"
paginate: 10
paginate_path: "/page:num/"
markdown: kramdown
theme: minima
future: true
plugins:
  - jekyll-paginate

logo: "/assets/images/logo.png"
