name: E SPORT
title: E SPORT
description: The best source for E-Sports news.
url: "https://kinanmjeed88.github.io"
baseurl: "/E-SPORT"
paginate: 10
paginate_path: "/page:num/"
markdown: kramdown
theme: minima
future: true
plugins:
  - jekyll-paginate

logo: "/assets/images/logo-1771731345804-1000180155.jpg"

facebook: "www.facebook.com"
instagram: "www.facebook.com"
tiktok: "www.facebook.com"
youtube: "www.facebook.com"
telegram: "https://t.me/E_sport0"